### ISSUE TITLE
jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag

### ISSUE THREAD

**Issue by thangaraj-26** [MogiePete/zabbix-systemd-service-monitoring#19]
Due to #SERVICE in zbx_service_discovery.sh i am getting following error.

jinja2.exceptions.TemplateSyntaxError: Missing end of comment tag

can we keep {SERVICE} instead of {#SERVICE} while making same changes in corresponding xml(Template) file.

**Comment by MogiePete** [comment]
#Service is the variable used by Zabbix. Removing the # would break the way Zabbix works.

See the snippet it from the template.

```
                        <item_prototype>
                            <name>{#SERVICE} Restart</name>
                            <type>0</type>
                            <snmp_community/>
                            <snmp_oid/>
                            <key>systemd.service.restart[{#SERVICE}]</key>
```
