### ISSUE TITLE
system.uptime.systemd not supported

### ISSUE THREAD

**Issue by alialtansaka** [MogiePete/zabbix-systemd-service-monitoring#2]
Hi

i got an error like that

Item: System uptime
Key: system.uptime.systemd
State: Not supported

also tried with: zabbix_agentd -t "system.uptime.systemd"

how can i solve this

thanks

**Comment by MogiePete** [comment]
@alialtansaka 

I have updated the user_parameter file along with the template file to reflect the working systemd.uptime command.

Please import the newest template or modify the key for System Uptime to systemd.uptime and copy over the new user_parameter file.
