### ISSUE TITLE
Timeout while executing a shell script.

### ISSUE THREAD

**Issue by fabjsousa** [MogiePete/zabbix-systemd-service-monitoring#21]
Hello, 

I've the zabbix-systemd-service-monitoring configured in several hosts, but in some cases on zabbix web I've this error **Timeout while executing a shell script.**

![image](https://user-images.githubusercontent.com/52783790/73536528-feee6c80-441d-11ea-92c1-65de2c1d062a.png)

If I run the script manually all the services are detected but on the web not

`[root@server1 ~]# /usr/local/bin/zbx_service_discovery.sh 
{"data":[{"{#SERVICE}": "firewalld"},{"{#SERVICE}": "nrpe"},{"{#SERVICE}": "ntpd"},{"{#SERVICE}": "postfix"},{"{#SERVICE}": "sshd"},{"{#SERVICE}": "service1"},{"{#SERVICE}": "service2"},{"{#SERVICE}": "zabbix-agent"}]}`

I've tried to change the **Timeout** value on **zabbix_agentd.conf** and in some case the error disappear and another not. For those who can execute the services aren't detected.

Any idea what is wrong?

Thank you.

**Comment by MogiePete** [comment]
Check SELinux and the Zabbix Agents logs.

**Comment by fabjsousa** [comment]
Fixed!!! 
I've to add a rule with semodule to permit the excution of the script.
Thank you.
