### ISSUE TITLE
"Value should be a JSON object." error.

### ISSUE THREAD

**Issue by yikiksistemci** [MogiePete/zabbix-systemd-service-monitoring#24]
Hi,
i using your template, but i have a problem. Zabbix was giving error "Value should be a JSON object."
i fixed problem.

**Comment by yikiksistemci** [comment]
But, i don't commit project.

`echo -n '{"data":[';for s in ${service_list}; do echo -n "{\"{#SERVICE}\":\"$s\"},";done | sed -e 's:\},$:\}:';echo -n ']}'
`

**Comment by MogiePete** [comment]
Thank you for the update.
