### ISSUE TITLE
Systemctl status service_name takes too much time

### ISSUE THREAD

**Issue by user9931** [MogiePete/zabbix-systemd-service-monitoring#27]
It can be only happens on slow systems

On my Vps (very cheap & small, openvz) its takes forever to show logs of sshd service, for example (maybe another). its about line 

  `UserParameter=systemd.service.status[*],$(systemctl status $1 2>/dev/null`

so its trying to show log and we dont need them. 

 ` UserParameter=systemd.service.status[*],$(systemctl status  --lines=0 $1 2>/dev/null`

work instantly.

**Comment by MogiePete** [comment]
Fixed.
